### ISSUE TITLE
Procedure names not predicted

### ISSUE THREAD

**Issue by Yanivmd** [eth-sri/debin#6]
Hi,
Thank you for making your project available to the community.

After training a model I ran the prediction step on several stripped (strip -g, as advised in #3) binaries.

Examining the output (readelf -s X), while some variables are predicted, *all procedure names* in the output files were predicted correctly. I found this a bit odd, so i renamed all procedure names manually to UNK_x (where x is the index in the symbol table) in the stripped file and ran the prediction again. This time all procedures *remained* UNK_x.

Note, prediction was performed as instructed in README - "python3 py/predict.py --binary mystripped --output  mystripped.output --elf_modifier cpp/modify_elf.so -two_pass --fp_model new_models/variable/x86/ --n2p_url http://localhost:8604"

What am I doing wrong?

Thanks.

**Comment by LostBenjamin** [comment]
This is expected behavior of `py/predict.py`. If symbol table is present, it will take function names from symbol table. Otherwise, it will predict function names (note that here function boundaries are inferred by BAP). `py/predict.py` is designed to be used in real world scenario, where users may input binaries with symbol table and debin would like to make prediction based on all available information.

For evaluation purposes, please use `py/evaluate.py`.

**Comment by urialon** [comment]
Hi @LostBenjamin,
So as I understand, the results in the paper ("Name prediction" in Table 3) do not include precision/recall of *function names*?
In other words - the experiments in the paper were conducted using `strip -g`, therefore function boundaries and function names were considered as given. Is that correct?

Thanks!

**Comment by LostBenjamin** [comment]
Your understanding is wrong.

In the paper, we considered function names as to be inferred and cleared them before prediction. So the results include precision/recall of function names. Function boundaries were considered given as stated in the paper.

We update the README for clarifying these points.
